dist: xenial
language: python
sudo: false
cache: pip
branches:
  only:
    - master

matrix:
  include:
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=checkmanifest
    - env: TOXENV=isort
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: pypy3.5-6.0
      env: TOXENV=pypy3
    - python: 3.7
      os: linux
      env: TOXENV=32bit TEST_32BIT=1

install:
  - pip install tox
script:
  - tox
after_success:
  - pip install coveralls
  - coveralls
